Etapa2/Models/Board.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using System.Linq;

namespace Etapa2.Models
{
    public class Board : Entity
    {
        [Required]
        [DataType(DataType.MultilineText)]
        public String Description { get; set; }

        [Required]
        public String User { get; set; }

        public IDictionary<string, BoardPermission> permissions = new Dictionary<string, BoardPermission>();

        public bool CanEdit(string user)
        {
            return (this.User == user || (permissions.Keys.Contains(user) && permissions[user].CanWrite));
        }
    }
}

Etapa2/Controllers/BoardsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Etapa2.Controllers.Common.Attributes;
using Etapa2.Models;
using Etapa2.Repository;
using Etapa2.Views.Entitys;

namespace Etapa2.Controllers
{
    [Authorization]
    public class BoardsController : Controller
    {
        private BoardMemoryRepository _repo_board = RepositoryLocator.GetBoardRepo();
        private BoardListMemoryRepository _repo_list = RepositoryLocator.GetBoardListRepo();
        private CardMemoryRepository _repo_cards = RepositoryLocator.GetCardRepo();
        private UserMemoryRepository _repo_users = RepositoryLocator.GetUserRepo();
        private int BoardsPerLine = 5;
        
        public ActionResult Index(string errormessage = "")
        {
            string user = User.Identity.Name;
            if (user == null)
                throw new ArgumentNullException("User");

            List<Board> allboards = _repo_board.GetBoardsThatUserCanUse(user).ToList();
            List<IEnumerable<Board>> boardsdivided = new List<IEnumerable<Board>>();
            int count;
            for (int i = 0; i < allboards.Count; i += BoardsPerLine)
            {
                count = (i + BoardsPerLine < allboards.Count) ? BoardsPerLine : allboards.Count - i;
                boardsdivided.Add(allboards.GetRange(i, count));
            }

            ViewBag.error = errormessage;
            ViewBag.BoardsPerLine = BoardsPerLine;
            return View("BoardsView", boardsdivided);
        }

        private int ListsPerLine = 5;
        public ActionResult Details(int id)
        {
            string user = User.Identity.Name;
            BoardDetails boardDetails = new BoardDetails();
            boardDetails.board = _repo_board.GetById(id);

            if (boardDetails.board == null)
            {
                return new HttpNotFoundResult("Board with id=" + id);
            }

            if (user == null || !_repo_board.CanUserViewBoard(id, user))
                return new HttpUnauthorizedResult();

            List<BoardList> alllists = _repo_list.GetListsById(id).OrderBy(list => list.BoardPosition).ToList();
            List<IEnumerable<BoardList>> listsdivided = new List<IEnumerable<BoardList>>();
            int count;
            for (int i = 0; i < alllists.Count; i += ListsPerLine)
            {
                count = (i + ListsPerLine < alllists.Count) ? ListsPerLine : alllists.Count - i;
                listsdivided.Add(alllists.GetRange(i, count));
            }

            boardDetails.canUserWrite = boardDetails.board.CanEdit(user);
            boardDetails.listsPerLine = this.ListsPerLine;
            boardDetails.listsDivided = listsdivided;
            boardDetails.numberOfLists = alllists.Count;

            return View("BoardDetail", boardDetails);
        }

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                string error = "";
                string user = User.Identity.Name;
                if(user == null)
                    return new HttpUnauthorizedResult();
                string name = collection["name"];
                if (!string.IsNullOrEmpty(name))
                {
                    string description = collection["desc"];
                    if (string.IsNullOrEmpty(description))
                        description = "( no description )";
                    _repo_board.Add(new Board { Description = description, User = user, Name = name, CreateDate = DateTime.Now });
                }
                else
                {
                    error = "Name field can't be blank!";
                }
                return RedirectToAction("Index", new { errormessage=error });
            }
            catch
            {
                return View("Error");
            }
        }
        
        //
        // GET: /Boards/Edit/5

        public ActionResult Edit(int id, string errormessage = "")
        {
            string user = User.Identity.Name;

            if (user == null)
                throw new ArgumentNullException("User");

            Board board = _repo_board.GetById(id);
            if (board == null)
            {
                return new HttpNotFoundResult("Board with id=" + id);
            }
            if (!_repo_board.CanUserWriteOnBoard(id, user))
                return new HttpUnauthorizedResult();

            ViewBag.editerror = errormessage;
            return View("BoardEdit", board);
        }

        //
        // POST: /Boards/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                string user = User.Identity.Name;
                Board board = _repo_board.GetById(id);

                if (!board.CanEdit(user))
                    return new HttpUnauthorizedResult();

                string name = collection["name"];
                string description = collection["desc"];
                if (string.IsNullOrEmpty(name))
                    name = board.Name;
                else if (name != board.Name && _repo_board.BoardNameExists(name, user))
                {
                    RedirectToAction("BoardEdit", new { errormessage = "Board name " + name + " already existes." });
                }

                _repo_board.UpdateBoard(id, name, description);
                return RedirectToAction("Index");
            }
            catch
            {
                return View("Error");
            }
        }

        [HttpPost]
        public ActionResult PermissionRemove(int boardid, string name, FormCollection collection)
        {
            try
            {
                string user = User.Identity.Name;
                Board board = _repo_board.GetById(boardid);

                if (!board.CanEdit(user))
                    return new HttpUnauthorizedResult();

                _repo_board.RemoveBoardPermissionTo(boardid, name);
                return RedirectToAction("Edit", "Boards", new { id = boardid });
            }
            catch
            {
                return View("Error");
            }
        }

        [HttpPost]
        public ActionResult PermissionChange(int boardid, string userperm, bool set, FormCollection collection)
        {
            Board board = _repo_board.GetById(boardid);
            string user = User.Identity.Name;

            if (!board.CanEdit(user))
                return new HttpUnauthorizedResult();

            if (board.permissions.Keys.Contains(userperm))
            {
                board.permissions[userperm].CanWrite = set;
            }
            return RedirectToAction("Edit", "Boards", new { id = boardid });
        }

        [HttpPost]
        public ActionResult PermissionAdd(int boardid, FormCollection collection)
        {
            string errormessage = "";
            Board board = _repo_board.GetById(boardid);
            string user = User.Identity.Name;

            if (!board.CanEdit(user))
                return new HttpUnauthorizedResult();

            string name = collection["permissionname"];
            string type = collection["permissiontype"];

            if (string.IsNullOrEmpty(type))
                errormessage = "Insert a type of permission";

            if (string.IsNullOrEmpty(name))
                errormessage += (errormessage==""?"I":" and i") + "nsert a name";

            else if (user==name || !_repo_users.DoesUserExist(name))
                errormessage = "User does not exists";

            if (errormessage == "")
            {
                BoardPermission permission = new BoardPermission { User = name, CanWrite = type == "rw" };
                board = _repo_board.UpdateBoard(boardid, permission);
                _repo_board.GiveBoardPermissionTo(boardid, name);
                ViewBag.permissionerror = "";
                return RedirectToAction("Edit", "Boards", new { id=boardid });
            }
            else
            {
                ViewBag.permissionerror = errormessage;
                return View("BoardEdit", board);
            }
        }

        //
        // GET: /Boards/Delete/5
 
        public ActionResult Delete(int id)
        {
            var list = _repo_list.GetById(id);
            if(!_repo_cards.GetCardsByListId(id).Any())
            {
                _repo_list.Remove(list);
            }
            return RedirectToAction("Details", new { id = list.BoardId });
        }

        [HttpPost]
        public JsonResult GetListsFromBoard(int id)
        {
            var board = _repo_board.GetById(id);
            var json = new List<string>();

            foreach (var item in _repo_list.GetListsById(board))
            {
                json.Add(item.Id+"");
                json.Add(item.Name);
            }
            return Json(new {list = json, len = json.Count}, JsonRequestBehavior.AllowGet);
        }
    }
}

Etapa2/Controllers/ListsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Etapa2.Controllers.Common.Attributes;
using Etapa2.Models;
using Etapa2.Repository;
using Etapa2.Views.Entitys;

namespace Etapa2.Controllers
{
    [Authorization]
    public class ListsController : Controller
    {
        private BoardListMemoryRepository _repo_list = RepositoryLocator.GetBoardListRepo();
        private CardMemoryRepository _repo_card = RepositoryLocator.GetCardRepo();
        private BoardMemoryRepository _repo_board = RepositoryLocator.GetBoardRepo();

        //
        // GET: /Lists/Details/5

        private int CardsPerLine = 7;
        public ActionResult Details(int id)
        {
            string user = User.Identity.Name;

            if (user == null)
                throw new ArgumentNullException("User");

            ListDetails listDetails = new ListDetails();
            BoardList list = listDetails.list = _repo_list.GetById(id);

            if (list == null)
            {
                return new HttpNotFoundResult("Board with id=" + id);
            }

            if (!_repo_board.CanUserViewBoard(list.BoardId, user))
                return new HttpUnauthorizedResult();

            List<Card> allcards = _repo_card.GetCardsByListId(id).OrderBy(card => card.BoardListPosition).ToList();
            List<IEnumerable<Card>> listsdivided = new List<IEnumerable<Card>>();
            int count;
            for (int i = 0; i < allcards.Count; i += CardsPerLine)
            {
                count = (i + CardsPerLine < allcards.Count) ? CardsPerLine : allcards.Count - i;
                listsdivided.Add(allcards.GetRange(i, count));
            }

            listDetails.cardsPerLine = this.CardsPerLine;
            listDetails.cardsDivided = listsdivided;
            listDetails.numberOfCards = allcards.Count;
            listDetails.canUserWrite = _repo_board.CanUserWriteOnBoard(list.BoardId, user);

            return View("ListDetail", listDetails);
        }


        //
        // POST: /Lists/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                string user = User.Identity.Name;
                if (user == null)
                    return new HttpUnauthorizedResult();
                string name = collection["name"];
                int position = int.Parse(collection["position"]);
                int boardId = int.Parse(collection["boardId"]);
                BoardList newbl = new BoardList();
                newbl.CreateDate = DateTime.Now;
                newbl.Name = name;
                newbl.BoardPosition = position;
                newbl.BoardId = boardId;

                int lid = _repo_list.Add(newbl);
                return RedirectToAction("Details", new {id = lid});
            }
            catch
            {
                return View("Error");
            }
        }
        
        //
        // GET: /Lists/Edit/5
 
        public ActionResult Edit(int id)
        {
            string user = User.Identity.Name;
            BoardList list = _repo_list.GetById(id);
            if (list == null)
                return new HttpNotFoundResult("List with ID=" + id + " doen't exist!");

            if (user == null || !_repo_board.CanUserWriteOnBoard(list.BoardId, user))
                return new HttpUnauthorizedResult();

            int countcards = _repo_card.GetCardsByListId(id).Count();
            string owner = _repo_board.GetById(list.BoardId).User;
            int listcount = _repo_list.GetListsById(list.BoardId).Count();
            ListEdit listedit = new ListEdit { list = list, user = owner, numberofcardslistcontains = countcards, numberoflistsinboard = listcount };

            return View("ListEdit", listedit);
        }

        //
        // POST: /Lists/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                string user = User.Identity.Name;
                BoardList list = _repo_list.GetById(id);
                if (list == null)
                    return new HttpNotFoundResult("List with ID=" + id + " doen't exist!");

                if (user == null || !_repo_board.CanUserWriteOnBoard(list.BoardId, user))
                    return new HttpUnauthorizedResult();
                
                string nameerror="", newname = collection["name"];
                int pos;
                if(collection["pos"] == null || !int.TryParse(collection["pos"], out pos)){
                    pos = list.BoardPosition;
                }
                 
                if(string.IsNullOrEmpty(newname)){
                    nameerror = "Insert a name...";
                }
                else if (newname == list.Name)
                {
                    nameerror = "Name is the same...";
                }
                else if (_repo_list.UserHasListNameInBoard(list, newname))
                {
                    nameerror = "This board already has a list with the name '" + newname + "'.";
                }

                if (nameerror == "")
                {
                    _repo_list.UpdateList(id, newname);
                    ViewBag.messagename = "Name changed!";
                    ViewBag.errorname = "";
                }
                else
                {
                    ViewBag.messagename = "";
                    ViewBag.errorname = nameerror;
                }
                if (pos != list.BoardPosition)
                {
                    _repo_list.UpdateList(id, pos);
                    ViewBag.messagepos = "Position changed!";
                }
                else
                    ViewBag.messagepos = "";

                return View("ListEdit", new ListEdit { list = list, user = _repo_board.GetById(list.BoardId).User,
                                                       numberofcardslistcontains = _repo_card.GetCardsByListId(id).Count(),
                                                       numberoflistsinboard = _repo_list.GetListsById(list.BoardId).Count()
                });
            }
            catch
            {
                return View("Error");
            }
        }

        //
        // POST: /Lists/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                string user = User.Identity.Name;
                BoardList list = _repo_list.GetById(id);
                if (list == null)
                    return new HttpNotFoundResult("List with ID=" + id + " doen't exist!");

                if (user == null || !_repo_board.CanUserWriteOnBoard(list.BoardId, user))
                    return new HttpUnauthorizedResult();

                _repo_list.Remove(list);

                return RedirectToAction("Details", "Boards", new { id = list.BoardId });
            }
            catch
            {
                return View("Error");
            }
        }

        [HttpPost]
        public JsonResult ChangeCardsOrder(int[] list, int id)
        {
            try
            {
                var i = 0;
                foreach (var item in list.Where(item => item != 0))
                {
                    if (_repo_card != null && _repo_card.GetById(item).BoardListPosition != (i + 1))
                        _repo_card.GetById(item).BoardListPosition = i + 1;
                    i++;
                }
                return Json(true, JsonRequestBehavior.AllowGet);
            }catch
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public JsonResult MoveCard(int listId, int cardId)
        {
            var card =_repo_card.GetById(cardId);
            card.BoardListId = listId;
            var pos = _repo_card.GetCardsByListId(listId).Count();
            _repo_card.SetPositionOfCard(ref card, pos);

            return Json(true, JsonRequestBehavior.AllowGet);
        }
    }
}

Etapa2/Views/Boards/BoardDetail.cshtml
@using Etapa2.Models
@using Etapa2.Views.Entitys
@model BoardDetails

@{
    ViewBag.Title = "BoardDetail - " + Model.board.Name;
}

<h2>Board <span style="color: cadetblue">@Model.board.Name</span> Details</h2>
<h3>Owner: @if (User.Identity.Name == Model.board.User){ <text>You</text> }else{ <text>@Model.board.User</text> }</h3>
<h3>Descripton: @Model.board.Description</h3>
<h3>Creation Date: @Model.board.CreateDate.ToShortDateString()</h3>

<br/><hr/><br/>

@if(Model.listsDivided.Any())
{
    <fieldset>
        <legend>@Model.board.Name - Lists</legend>
        <table style="width: 100%">
            @foreach(var listDivision in Model.listsDivided)
            {
                <tr style="height: 70px;">

                    @foreach (BoardList list in listDivision)
                    {
                        <td class="filledboard" style="width: @(100/Model.listsPerLine)%; position: relative;">
                            <div style="position: absolute; top: 0; width: 100%; height: 100%;">
                                <div style="position: absolute; top: 0; right: 0; font-size: 70%; padding-right: 5px">@list.CreateDate.ToShortDateString()</div>
                                <br/>
                                <div style=" text-align:center; margin-right: 10px;">@Html.ActionLink(list.Name, "Details", "Lists", new {id = list.Id}, null)</div>
                                    @if (Model.canUserWrite){
                                        <a href="/Lists/Edit/@list.Id"><img src="../../Content/img/editlist.jpg" width="20" height="20"/> </a>
                                    }
                            </div>
                        </td>
                    }
                    @if (listDivision.Count() != Model.listsPerLine)
                    {
                        int n = Model.listsPerLine - listDivision.Count();
                        for (int i = 0; i < n; i++)
                        {
                            <td class="empty" style="width: @(100/Model.listsPerLine)%"> </td>
                        }
                    }
                </tr>
            }
        </table>
    </fieldset>
}
@if(!Model.listsDivided.Any())
{
    <div style="border: solid 2px #e8eef4; height: 150px; text-align: center;">
        @if(Model.canUserWrite){
            <h2 style=" color: cadetblue;">You don't have any lists in this board!</h2>
            <h2 style=" color: cadetblue;">Create a new one bellow.</h2>
        }else{
            <h2 style=" color: cadetblue;">There are no lists in this board!</h2>
        }
    </div>
}

@if(Model.canUserWrite){
    <br/><hr/><br/>

    <h2>Create a new List!</h2>

    using (Html.BeginForm("Create", "Lists"))
    {
        <input type="hidden" name="boardId" value="@Model.board.Id"/>
        <fieldset>
            <legend>New List</legend>
            <div>Name: <span style="margin-left: 40px">@Html.TextBox("name", "", new { id = "name" })</span></div>
            @if (Model.numberOfLists == 0)
            {
                <input type="hidden" name="position" value="1"/>
            }
            @if(Model.numberOfLists!=0){
            
                List<SelectListItem> posList = new List<SelectListItem>();
                int i = 1;
                for(; i <= Model.numberOfLists; ++i)
                {
                    posList.Add(new SelectListItem {Selected = false, Text = i.ToString(), Value = i.ToString()});
                }
                posList.Add(new SelectListItem {Selected = true, Text = i.ToString(), Value = i.ToString()});
            
                <div style="position: relative"> <span style="position: absolute; top: 0">Position:</span> <span style="margin-left: 82px">@Html.DropDownList("position", posList)</span></div>
            }
            <button type="submit" onclick="javaScript: return VerifyElementNotNull('name', 'Name');">Create!</button>
            <span id="inputError" style="color: red; margin-left: 30px"> </span>
        </fieldset>
    }
}
@Html.ActionLink("Back","Index")

Etapa2/Views/Boards/BoardEdit.cshtml
@using Etapa2.Models
@model Board
@{bool PageEditable = Model.CanEdit(User.Identity.Name); }
@{bool IsOwner = User.Identity.Name==Model.User; }

@{
    ViewBag.Title = "BoardEdit - " + Model.Name;
}

<h2>Board <span style="color: cadetblue;">@Model.Name</span> Details</h2>
<h3>Owner: @if (IsOwner) { <text>You</text> }else{<text>@Model.User</text>}</h3>
<h3>Creation Date: @Model.CreateDate.ToShortDateString()</h3>

<fieldset>
    <legend>Edit Board</legend>
    <br />
        <div>
            <fieldset>
                <legend>Permissions</legend>
                    <table border="1">
                        <thead>
                            <tr>
                                <td style="width:250px; text-align:center;">User</td><td>Can Write</td><td>Remove</td>
                            </tr>
                        </thead>
                        @if(Model.permissions.Count != 0){
                        <tbody>
                            @foreach (BoardPermission permission in Model.permissions.Values)
                            {
                                <tr>
                                    <td>
                                        @permission.User
                                    </td>
                                    <td style="text-align:center;">
                                        @if (IsOwner)
                                        { 
                                            if(permission.CanWrite){
                                                using (Html.BeginForm("PermissionChange", "Boards", new { boardid = Model.Id, userperm = permission.User, set = false }))
                                                {
                                                    <input type="image" src="../../Content/img/CheckboxTrue.png" />
                                                }
                                            }else{
                                                using (Html.BeginForm("PermissionChange", "Boards", new { boardid = Model.Id, userperm = permission.User, set = true }))
                                                {
                                                    <input type="image" src="../../Content/img/CheckboxFalse.png" />
                                                }
                                            }
                                        }
                                        else
                                        {
                                            @Html.CheckBox("canW", permission.CanWrite, new { disabled = "disabled" })
                                        }
                                    </td>
                                    <td style="text-align:center;">
                                        @using (Html.BeginForm("PermissionRemove", "Boards", new { boardid = Model.Id, name = permission.User }))
                                        {
                                            if (IsOwner)
                                            { 
                                                <input width="20" height="20" type="image" name="done_5" src="../../Content/img/remove.jpg" onclick="return ConfirmRemovePermission();"/>
                                            }
                                            else
                                            {
                                                <img width="20" height="20" src="../../Content/img/remove.bmp" />
                                            }
                                        }
                                    </td>
                                </tr>
                            }
                        </tbody>
                        }
                        @if (Model.permissions.Count == 0)
                        {
                            <tbody>
                                <tr>
                                    <td colspan="3" style="color: cadetblue; text-align:center;">Only you have permission to view and edit this board</td>
                                </tr>
                            </tbody>
                        }
                    </table>
                    @if (IsOwner)
                    { 
                        <div style="width:100%; padding-top:10px;">
                            @using (Html.BeginForm("PermissionAdd", "Boards", new { boardid = Model.Id }))
                            {
                                <button type="submit">Add New User!</button>
                                <label for="permissionname">Name: </label><input type="text" id="permissionname" name="permissionname" value=""/>
                                <label for="permissionaddtype" style="padding-left:20px">Permission:</label> 
                                <span id="permissionaddtype">
                                    <label for="permissiontypewrite" style="padding-left:10px;">Can View and Edit:</label>
                                    <input id="permissiontypewrite" type="radio" name="permissiontype" value="rw"/>
                                    <label for="permissiontyperead" style="padding-left:10px;">Can only View:</label>
                                    <input id ="permissiontyperead" type="radio" name="permissiontype" value="r"/>
                                </span> 
                        
                                <div style="color: red;">@ViewBag.permissionerror</div>
                            }
                        </div>
                    }
                </fieldset>
        </div>
    <br />
    @using (Html.BeginForm("Edit", "Boards"))
    {
        <br />
        <div>Name: <span style="margin-left: 40px">@Html.TextBox("name", Model.Name)</span></div>
        <div style="position: relative"> <span style="position: absolute; top: 0">Description:</span> <span style="margin-left: 82px">@Html.TextArea("desc", Model.Description, new { @class = "textArea" })</span></div>
        <button type="submit">Edit!</button>
    }
    <span style="color: red; margin-left: 30px">@ViewBag.editerror</span>
</fieldset>

<script type="text/javascript"">
    function ConfirmRemovePermission() {
        debugger;
        if (confirm('Are you sure you want to denie this user from using this board?')) {
            return true;
        } else {
            return false;
        }
    }
</script>

Etapa2/Views/Boards/BoardsView.cshtml
@using System.Linq
@using Etapa2.Models
@model IEnumerable<IEnumerable<Board>>
@{
    ViewBag.Title = "Trello PIp2 - Boards";
}
<h2>Your Boards</h2>

@if(Model.Any())
{
    <table style="width: 100%">
        @foreach(var boardDivision in Model)
        {
            <tr style="height: 150px;">

                @foreach (Board board in boardDivision)
                {
                    <td class="filledboard" style="width: @(100/ViewBag.BoardsPerLine)%; position: relative;">
                        <div style="position: absolute; top: 0; width: 100%; height: 100%;">
                            <div style="position: absolute; top: 0; right: 0; font-size: 70%; padding-right: 5px">@board.CreateDate.ToShortDateString()</div>
                            <div style="position: absolute; top: 0; left: 0; font-size: 70%;">Board owner: @if(board.User == User.Identity.Name){<text>You</text>}else{<text>@board.User</text>}</div>
                            <br/>
                            <div style="text-align: center; margin-right: 10px;">@Html.ActionLink(board.Name, "Details", new {id = board.Id})</div>
                            <br/><br/>
                            <div style="text-align: center; margin-right: 10px;">@CommonViewFunctions.LimitText(board.Description)</div>
                            <span style="position:absolute; bottom:0; right:10px;">
                                @if(board.CanEdit(User.Identity.Name)){
                                    <a href="Boards/Edit/@board.Id"> <img src="../../Content/img/edit.jpg" width="15" height="15"/> </a>
                                }else{
                                    <img src="../../Content/img/editNo.png" width="15" height="15"/>
                                }
                            </span>
                        </div>
                    </td>
                }
                @if(boardDivision.Count() != ViewBag.BoardsPerLine)
                {
                    int n = ViewBag.BoardsPerLine - boardDivision.Count();
                    for (int i = 0; i < n; i++)
                    {
                        <td class="empty" style="width: @(100/ViewBag.BoardsPerLine)%"> </td>
                    }
                }
            </tr>
        }
    </table>
}
@if(!Model.Any())
{
<div style="border: solid 2px #e8eef4; height: 150px; text-align: center;">
    <h2 style=" color: cadetblue;">You don't have any boards!</h2>
    <h2 style=" color: cadetblue;">Create a new one to get started.</h2>
</div>
}
<br/><hr/><br/>

<h2>Create a new Board!</h2>

@using (Html.BeginForm("Create", "Boards"))
{
    <fieldset>
        <legend>New Board</legend>
        <div>Name: <span style="margin-left: 40px">@Html.TextBox("name", "", new { id = "name" })</span></div>
        <div style="position: relative"> <span style="position: absolute; top: 0">Description:</span> <span style="margin-left: 82px">@Html.TextArea("desc", new { @class = "textArea" })</span></div>
        <button type="submit" onclick="javaScript: return VerifyElementNotNull('name', 'Name');">Create!</button>
        <span id="inputError" style="color: red; margin-left: 30px"> @ViewBag.error </span>
    </fieldset>
}